export type Category = 'On-Site' | 'Business' | 'Production' | 'Travel';

export interface Hint {
  en: string;
  cn: string;
}

export interface Scenario {
  id: string;
  title: string;
  titleCn: string;
  icon: string;
  category: Category;
  aiRole: string;
  aiRoleCn: string;
  description: string;
  hints: Hint[];
}

export const SCENARIOS: Scenario[] = [
  // ── Original 6 ────────────────────────────────────────────────────────────
  {
    id: 'venue-walkthrough',
    title: 'Venue Walkthrough',
    titleCn: '带客户参观场地',
    icon: '🏛️',
    category: 'On-Site',
    aiRole: 'First-time client',
    aiRoleCn: '首次参观的客户',
    description: 'Walk a client through the event space for the first time',
    hints: [
      { en: "Let me walk you through the space from the entrance.", cn: "让我从入口开始带您参观场地。" },
      { en: "The maximum seated capacity is around 350 guests.", cn: "最大坐席容量约为350人。" },
      { en: "The lighting is fully programmable to match your brand palette.", cn: "灯光完全可编程，可以匹配您的品牌色调。" },
      { en: "We have a dedicated green room with full AV access.", cn: "我们有专属候场室，配备完整的AV设备。" },
      { en: "We're a five-minute walk from the nearest train station.", cn: "距离最近的火车站步行仅需五分钟。" },
      { en: "For a cocktail reception, we can hold up to 500 guests.", cn: "鸡尾酒式招待会最多可容纳500位宾客。" },
    ],
  },
  {
    id: 'av-briefing',
    title: 'AV & Tech Briefing',
    titleCn: '音视频技术简报',
    icon: '🎛️',
    category: 'Production',
    aiRole: 'Lead AV technician',
    aiRoleCn: '音视频技术主管',
    description: 'Brief the lead AV technician before a major event',
    hints: [
      { en: "The stage is 12 metres wide and the ceiling height is 8 metres.", cn: "舞台宽12米，天花板高度为8米。" },
      { en: "We're going with a full L-C-R speaker setup for the main hall.", cn: "主厅采用完整的左-中-右扬声器配置。" },
      { en: "We need front projection — the ambient light will be controlled.", cn: "我们需要正投方案，环境光会受到控制。" },
      { en: "The keynote speaker needs a clip-on lavalier and confidence monitors.", cn: "主讲嘉宾需要领夹式麦克风和提词屏。" },
      { en: "Can you give me a final signal flow check two hours before doors open?", cn: "能在开门前两小时给我做最终信号流检查吗？" },
      { en: "Let me pull up the technical rider for you.", cn: "让我调出技术规格清单给您看。" },
    ],
  },
  {
    id: 'client-pitch',
    title: 'Client Concept Pitch',
    titleCn: '向客户提案',
    icon: '💼',
    category: 'Business',
    aiRole: 'Skeptical marketing director',
    aiRoleCn: '持怀疑态度的市场总监',
    description: 'Present your event concept to a skeptical new client',
    hints: [
      { en: "What sets us apart is our focus on immersive brand storytelling.", cn: "我们的差异在于专注于沉浸式品牌叙事体验。" },
      { en: "Every touchpoint is designed around your brand identity.", cn: "每个接触点都围绕您的品牌形象设计。" },
      { en: "The headline experience will be a live activation guests can't ignore.", cn: "核心体验将是一个让宾客无法忽视的现场互动装置。" },
      { en: "We have a full contingency plan for any technical failure.", cn: "针对任何技术故障，我们都有完整的应急预案。" },
      { en: "Based on your brief, I'd like to walk you through the budget breakdown.", cn: "根据您的需求简报，我想带您了解预算分配情况。" },
      { en: "The majority of the budget goes directly into the guest experience.", cn: "大部分预算直接用于提升宾客体验。" },
    ],
  },
  {
    id: 'day-of-crisis',
    title: 'Day-Of Crisis',
    titleCn: '活动当天突发危机',
    icon: '🚨',
    category: 'On-Site',
    aiRole: 'Venue ops manager',
    aiRoleCn: '场馆运营经理',
    description: 'Handle an emergency two hours before the event starts',
    hints: [
      { en: "Let's stay calm. Give me the approved vendor list right now.", cn: "保持冷静。请立刻给我看已审批的供应商名单。" },
      { en: "Yes, call Metro. I'll go brief the client personally.", cn: "好，联系Metro餐饮。我亲自去向客户说明情况。" },
      { en: "Let me escalate this — I'll handle the client directly.", cn: "让我来处理这件事，我直接跟客户沟通。" },
      { en: "Keep the AV team going — we can't afford to stop now.", cn: "让AV团队继续工作，我们现在不能停下来。" },
      { en: "What's our worst-case scenario if we can't resolve this in 30 minutes?", cn: "如果30分钟内解决不了，最坏的情况是什么？" },
      { en: "I need a status update from every department head in five minutes.", cn: "五分钟后我需要每个部门负责人的情况汇报。" },
    ],
  },
  {
    id: 'vendor-negotiation',
    title: 'Vendor Negotiation',
    titleCn: '与供应商谈判',
    icon: '🤝',
    category: 'Business',
    aiRole: 'Supplier defending price',
    aiRoleCn: '坚持报价的供应商',
    description: 'Negotiate contract terms with a supplier holding firm on price',
    hints: [
      { en: "I understand your position, but we need to find middle ground.", cn: "我理解您的立场，但我们需要找到一个折中方案。" },
      { en: "Could we look at adjusting the payment terms instead?", cn: "我们能不能考虑调整付款条款来代替降价？" },
      { en: "If we commit to two events this year, what flexibility do you have?", cn: "如果我们承诺今年合作两场活动，您有多少灵活空间？" },
      { en: "What's the minimum package that still delivers the premium look?", cn: "在保持高端效果的前提下，最低配置方案是什么？" },
      { en: "Can we revisit the scope — what's negotiable on the deliverables?", cn: "我们能重新讨论项目范围吗？哪些交付项是可以协商的？" },
      { en: "I need to take this back to my client before I can commit.", cn: "我需要先跟客户确认再做决定。" },
    ],
  },
  {
    id: 'post-event-debrief',
    title: 'Post-Event Debrief',
    titleCn: '活动后复盘',
    icon: '📋',
    category: 'Business',
    aiRole: 'Client reviewing results',
    aiRoleCn: '复盘活动效果的客户',
    description: 'Lead a post-event debrief with the client',
    hints: [
      { en: "Thank you for the feedback — let me address each point directly.", cn: "感谢您的反馈，让我逐一回应每个问题。" },
      { en: "For registration, we'll implement a pre-assigned lane system next time.", cn: "关于签到环节，下次我们将实施预分配通道制度。" },
      { en: "The keynote success came down to our pre-event technical rehearsal.", cn: "主题演讲的成功主要归功于我们活动前的技术彩排。" },
      { en: "My honest recommendation for September would be to start setup 30 minutes earlier.", cn: "对于九月的活动，我的诚实建议是提前30分钟开始布置。" },
      { en: "We'll put together a full post-event report with data by end of week.", cn: "我们将在本周末前提供一份包含数据的完整活动总结报告。" },
      { en: "I'd like to schedule a follow-up call to finalise the September brief.", cn: "我想约一次跟进电话，敲定九月活动的需求简报。" },
    ],
  },

  // ── 6 New Scenarios ────────────────────────────────────────────────────────
  {
    id: 'staff-briefing',
    title: 'Staff Briefing',
    titleCn: '开门前员工简报',
    icon: '📢',
    category: 'On-Site',
    aiRole: 'Event floor supervisor',
    aiRoleCn: '活动现场主管',
    description: 'Brief your on-site team 45 minutes before doors open',
    hints: [
      { en: "Doors open in 45 minutes — I want everyone clear on their station.", cn: "还有45分钟开门，我要确保每个人都清楚自己的位置。" },
      { en: "If a guest has a complaint, radio me first — don't handle it alone.", cn: "如果宾客有投诉，先用对讲机联系我，不要自行处理。" },
      { en: "VIP guests arrive at the side entrance — escort them directly to the lounge.", cn: "VIP宾客从侧门入场，请直接护送他们前往贵宾室。" },
      { en: "We are running five minutes behind on catering setup — keep guests in the foyer until I give the signal.", cn: "餐饮布置比计划晚了五分钟，在我发出信号前请将宾客留在门厅。" },
      { en: "Any questions? Speak now — once the doors open, I need everyone focused.", cn: "有任何问题现在说——一旦开门，我需要所有人全神贯注。" },
      { en: "Remember: smile, stay calm, and escalate anything unusual straight to me.", cn: "记住：保持微笑，沉着冷静，任何异常情况立即上报给我。" },
    ],
  },
  {
    id: 'vip-guest-handling',
    title: 'VIP Guest Issue',
    titleCn: '处理VIP宾客问题',
    icon: '⭐',
    category: 'On-Site',
    aiRole: 'Unhappy VIP guest',
    aiRoleCn: '不满意的VIP宾客',
    description: 'Resolve an on-the-spot complaint from a VIP guest',
    hints: [
      { en: "I completely understand your concern, and I'm going to fix this right now.", cn: "我完全理解您的顾虑，我现在就去解决。" },
      { en: "Allow me to personally escort you to a different table.", cn: "请允许我亲自带您到另一张桌子。" },
      { en: "Your experience tonight is our highest priority — please give me two minutes.", cn: "您今晚的体验是我们的首要任务，请给我两分钟。" },
      { en: "I apologise for this — it's not the standard we set for ourselves.", cn: "对此我深感抱歉，这不是我们为自己设定的标准。" },
      { en: "I'll make sure the event manager is personally aware of your feedback.", cn: "我会确保活动负责人亲自了解您的反馈。" },
      { en: "Can I offer you a drink while we sort this out?", cn: "我们处理这件事的时候，能为您奉上一杯饮品吗？" },
    ],
  },
  {
    id: 'sponsorship-pitch',
    title: 'Sponsorship Pitch',
    titleCn: '赞助商推介',
    icon: '🏆',
    category: 'Business',
    aiRole: 'Corporate sponsorship manager',
    aiRoleCn: '企业赞助经理',
    description: 'Pitch a sponsorship package to a corporate brand',
    hints: [
      { en: "This event reaches 800 decision-makers from the luxury retail sector.", cn: "此次活动将触达800位来自奢侈品零售领域的决策者。" },
      { en: "The naming rights package includes stage branding, digital assets, and a speaking slot.", cn: "命名权套餐包括舞台品牌展示、数字资产和演讲机会。" },
      { en: "We can tailor the activation to align with your Q4 campaign.", cn: "我们可以定制互动活动以配合您的第四季度营销计划。" },
      { en: "Last year's headline sponsor saw a 22% uplift in brand recall among attendees.", cn: "去年的主要赞助商在参与者中的品牌记忆度提升了22%。" },
      { en: "I can send you the full sponsorship prospectus by end of day.", cn: "我可以在今天结束前将完整的赞助商手册发送给您。" },
      { en: "What activation format works best for your audience right now?", cn: "目前哪种互动形式最适合您的受众群体？" },
    ],
  },
  {
    id: 'budget-presentation',
    title: 'Budget Presentation',
    titleCn: '预算汇报',
    icon: '💰',
    category: 'Business',
    aiRole: 'Client questioning costs',
    aiRoleCn: '对费用提出质疑的客户',
    description: 'Defend your event budget to a cost-conscious client',
    hints: [
      { en: "Let me walk you through where each line item comes from.", cn: "让我带您了解每一项费用的来源。" },
      { en: "The AV cost is higher because we're using a fully redundant system — no single point of failure.", cn: "AV费用较高，因为我们使用了完全冗余的系统，不存在单点故障。" },
      { en: "If we need to reduce the budget, I'd suggest we look at the print collateral first.", cn: "如果需要削减预算，我建议我们首先考虑减少印刷材料。" },
      { en: "This cost protects you from a much bigger problem on the day.", cn: "这笔费用是为了保护您在活动当天避免更大的问题。" },
      { en: "The venue hire is non-negotiable at this stage — we signed the contract last month.", cn: "场地租金在这个阶段无法协商，我们上个月已经签署了合同。" },
      { en: "I can provide three alternative options at different price points by tomorrow.", cn: "我可以在明天提供三个不同价位的备选方案。" },
    ],
  },
  {
    id: 'catering-coordination',
    title: 'Catering Coordination',
    titleCn: '餐饮团队协调',
    icon: '🍽️',
    category: 'Production',
    aiRole: 'Head chef on-site',
    aiRoleCn: '现场主厨',
    description: 'Coordinate with the catering team during event setup',
    hints: [
      { en: "The client confirmed a three-course sit-down dinner for 280 covers.", cn: "客户确认了280人份的三道菜正式晚宴。" },
      { en: "Service needs to begin at exactly 19:30 — can you commit to that?", cn: "上菜需要在19:30准时开始，您能保证做到吗？" },
      { en: "We have six guests with dietary restrictions — I'll send you the full list now.", cn: "有六位宾客有饮食限制，我现在就把完整名单发给您。" },
      { en: "The kitchen access is through the service corridor — do not use the main entrance.", cn: "厨房通道走服务走廊，不要走主入口。" },
      { en: "Canapes need to circulate for 45 minutes before we move guests into the main hall.", cn: "在将宾客引入主厅之前，开胃小食需要传递45分钟。" },
      { en: "What's your staffing plan for the dessert service?", cn: "甜点服务环节您的人员安排是什么？" },
    ],
  },
  {
    id: 'stage-manager-handoff',
    title: 'Stage Manager Handoff',
    titleCn: '交接给舞台监督',
    icon: '🎭',
    category: 'Production',
    aiRole: 'Incoming stage manager',
    aiRoleCn: '接班的舞台监督',
    description: 'Hand the running order to the stage manager before the show',
    hints: [
      { en: "Here's the running order — we have six segments across 90 minutes.", cn: "这是节目单，90分钟内共六个环节。" },
      { en: "The keynote is the anchor — everything else flexes around it.", cn: "主题演讲是核心，其他所有环节都围绕它灵活调整。" },
      { en: "We have a hard out at 22:00 — the venue has a strict noise curfew.", cn: "我们必须在22:00前结束，场地有严格的噪音宵禁规定。" },
      { en: "If we run over on the panel, cut the Q&A short — don't touch the keynote.", cn: "如果圆桌讨论超时，缩短问答环节，但不要动主题演讲的时间。" },
      { en: "Radio channel 3 is yours — I'm on channel 1 with the client.", cn: "对讲机频道3是你的，我在频道1上联系客户。" },
      { en: "Walk me through your cue sheet — I want to make sure we're aligned.", cn: "带我看一下你的提示单，我要确保我们步调一致。" },
    ],
  },

  // ── Exhibitor-side scenarios (working the booth at an overseas show) ──────
  {
    id: 'booth-qualification',
    title: 'Booth Visitor Qualification',
    titleCn: '展位访客快速甄别',
    icon: '🧲',
    category: 'On-Site',
    aiRole: 'Walk-up trade visitor',
    aiRoleCn: '主动走来的专业观众',
    description: 'Qualify a walk-up visitor at your booth in under two minutes',
    hints: [
      { en: "Welcome! What brings you to the show this year?", cn: "欢迎！您今年来展会主要关注什么？" },
      { en: "Are you currently sourcing, or exploring options for next year?", cn: "您是正在采购，还是在为明年考察方案？" },
      { en: "What volume are you typically working with?", cn: "您通常的采购量是多少？" },
      { en: "Let me scan your badge so I can send you the full catalogue.", cn: "让我扫一下您的胸卡，稍后把完整目录发给您。" },
      { en: "Our regional manager handles your market — can I set up a call this week?", cn: "我们的区域经理负责您的市场，这周安排一个电话可以吗？" },
      { en: "That's exactly what our new line addresses — do you have two minutes?", cn: "这正是我们新产品线要解决的问题，您有两分钟吗？" },
    ],
  },
  {
    id: 'technical-qa-booth',
    title: 'Technical Q&A at the Booth',
    titleCn: '展位技术问答',
    icon: '🔧',
    category: 'On-Site',
    aiRole: 'Engineer asking specs',
    aiRoleCn: '询问技术规格的工程师',
    description: 'Answer detailed spec questions from a technical buyer without freezing',
    hints: [
      { en: "Great question — let me pull up the exact spec sheet for you.", cn: "问得好——让我调出准确的规格表给您看。" },
      { en: "The unit is rated for continuous operation at up to 45 degrees.", cn: "该设备可在最高45度环境下连续运行。" },
      { en: "It's fully certified — CE, UL and RoHS documentation is available.", cn: "产品已完全认证——CE、UL和RoHS文件齐全。" },
      { en: "I don't want to give you a wrong number — let me confirm with our engineer.", cn: "我不想给您错误数据——让我和工程师确认一下。" },
      { en: "Compared with the previous model, power draw is down eighteen percent.", cn: "与上一代相比，功耗降低了18%。" },
      { en: "We can customise that parameter for orders above the minimum quantity.", cn: "超过最低订购量的订单，该参数可以定制。" },
    ],
  },
  {
    id: 'customs-freight-crisis',
    title: 'Customs & Freight Crisis',
    titleCn: '清关物流危机',
    icon: '📦',
    category: 'Production',
    aiRole: 'Show freight contractor',
    aiRoleCn: '展会物流承包商',
    description: 'Your booth crates are stuck in customs two days before opening',
    hints: [
      { en: "Our crates are held at customs — what paperwork is missing exactly?", cn: "我们的展品箱被海关扣留了——具体缺什么文件？" },
      { en: "I can have the commercial invoice and ATA carnet re-sent within the hour.", cn: "我可以在一小时内重新发送商业发票和ATA单证册。" },
      { en: "What's the latest possible delivery slot that still makes opening day?", cn: "最晚什么时间送达还能赶上开展日？" },
      { en: "If the main shipment misses the deadline, what are our rental options on-site?", cn: "如果主货运赶不上，现场有哪些租赁方案？" },
      { en: "Please escalate this with your customs broker — I'll cover the express fee.", cn: "请让你们的报关行加急处理——加急费我们承担。" },
      { en: "I need a status update every two hours until the crates clear.", cn: "在货物清关之前，我需要每两小时一次的进度更新。" },
    ],
  },
  {
    id: 'services-desk',
    title: 'Show Services Desk',
    titleCn: '展会服务台办事',
    icon: '🛎️',
    category: 'Production',
    aiRole: 'Services desk agent',
    aiRoleCn: '服务台工作人员',
    description: 'Order power, internet and labour at the show services desk',
    hints: [
      { en: "I need a 20-amp circuit and a hardwired internet line for booth 2214.", cn: "2214展位需要一条20安培电路和一条有线网络。" },
      { en: "What's the rate difference between advance order and show-site order?", cn: "提前预订和现场订购的价格差多少？" },
      { en: "We'll need two labourers for one hour tomorrow morning for the hang sign.", cn: "明早我们需要两名工人工作一小时，安装悬挂标志。" },
      { en: "Can you confirm the power drop location matches our booth plan?", cn: "能确认电源接入点位置和我们的展位图一致吗？" },
      { en: "Who do I call if the internet goes down during show hours?", cn: "展会期间网络中断的话，我该联系谁？" },
      { en: "Please put all charges on our master account — here's the credential.", cn: "所有费用请记入我们的主账户——这是凭证。" },
    ],
  },
  {
    id: 'networking-reception',
    title: 'Networking Reception',
    titleCn: '行业招待会社交',
    icon: '🥂',
    category: 'Business',
    aiRole: 'Industry peer at reception',
    aiRoleCn: '招待会上的同行',
    description: 'Make small talk and build a contact at the industry evening reception',
    hints: [
      { en: "How's the show been for you so far? Busy booth?", cn: "展会到目前为止怎么样？展位人多吗？" },
      { en: "We're on the exhibitor side — hall four, the LED wall you can't miss.", cn: "我们是参展商——四号馆，那面很显眼的LED墙就是我们。" },
      { en: "What did you think of this morning's keynote?", cn: "您觉得今天上午的主题演讲怎么样？" },
      { en: "We should stay in touch — are you on LinkedIn?", cn: "我们应该保持联系——您用LinkedIn吗？" },
      { en: "If you're ever sourcing in our category, I'd love to show you the range.", cn: "如果您以后需要采购我们这个品类，我很乐意带您看看产品线。" },
      { en: "It was great meeting you — enjoy the rest of the show.", cn: "很高兴认识您——祝您展会顺利。" },
    ],
  },

  // ── Batch 3: high-frequency "freeze moments" ─────────────────────────────
  {
    id: 'self-introduction',
    title: '30-Second Self-Intro',
    titleCn: '30秒自我介绍',
    icon: '👋',
    category: 'Business',
    aiRole: 'Potential partner you just met',
    aiRoleCn: '刚认识的潜在合作伙伴',
    description: 'Introduce yourself and your company clearly in under a minute',
    hints: [
      { en: "Hi, I'm Wei — I run event production for a Shanghai-based agency.", cn: '您好，我是Wei，负责一家上海机构的活动制作。' },
      { en: 'We specialise in large-format exhibitions for tech and auto brands.', cn: '我们专注于为科技和汽车品牌打造大型展览。' },
      { en: 'In one line: we make sure your brand looks flawless on the show floor.', cn: '一句话概括：我们确保您的品牌在展会现场完美呈现。' },
      { en: 'We handled 40 international shows last year across Europe and the Gulf.', cn: '去年我们在欧洲和海湾地区承接了40场国际展会。' },
      { en: 'What about you — what brings you to this show?', cn: '您呢？是什么让您来参加这次展会？' },
      { en: "Here's my card — I'd love to find a reason to work together.", cn: '这是我的名片，我很希望能找到合作的机会。' },
    ],
  },
  {
    id: 'lead-follow-up',
    title: 'Post-Show Lead Follow-Up',
    titleCn: '展后线索跟进电话',
    icon: '📞',
    category: 'Business',
    aiRole: 'Lead you met at the show',
    aiRoleCn: '展会上认识的潜在客户',
    description: 'Call a lead a week after the show and move toward a meeting',
    hints: [
      { en: 'Hi, we met at booth 2214 at Automechanika — you asked about lead times.', cn: '您好，我们在Automechanika的2214展位见过，您当时问过交货周期。' },
      { en: "I'm following up on the samples you were interested in.", cn: '我想跟进一下您感兴趣的样品。' },
      { en: 'Would a short call next week work to walk through pricing?', cn: '下周方便安排一个简短电话，过一下报价吗？' },
      { en: "I've attached the catalogue and the spec sheet we discussed.", cn: '我已附上我们讨论过的目录和规格表。' },
      { en: 'What would you need from us to move this forward?', cn: '您需要我们提供什么才能推进这件事？' },
      { en: "No pressure — I just don't want a good conversation to go cold.", cn: '不急——我只是不想让一次好的交流不了了之。' },
    ],
  },
  {
    id: 'media-interview',
    title: 'Media Interview at the Booth',
    titleCn: '展位媒体采访',
    icon: '🗞️',
    category: 'On-Site',
    aiRole: 'Trade press journalist',
    aiRoleCn: '行业媒体记者',
    description: 'Handle an on-the-spot interview from a trade journalist',
    hints: [
      { en: 'Thanks for stopping by — happy to give you two minutes.', cn: '谢谢您光临，我很乐意给您两分钟。' },
      { en: 'The headline for us this year is our new modular booth system.', cn: '我们今年的重点是全新的模块化展位系统。' },
      { en: 'What makes it newsworthy is the 50% faster build time.', cn: '它的新闻价值在于搭建时间缩短了50%。' },
      { en: "I'd rather not comment on pricing, but I can talk about the technology.", cn: '价格我不便评论，但我可以谈谈技术。' },
      { en: 'Let me connect you with our marketing lead for the full press kit.', cn: '让我帮您联系我们的市场负责人，索取完整的新闻资料。' },
      { en: 'Can I confirm how you\'ll attribute this quote before we finish?', cn: '结束前，我能确认一下这句话您会如何署名引用吗？' },
    ],
  },
  {
    id: 'show-teardown',
    title: 'Show Teardown & Strike',
    titleCn: '展会拆撤协调',
    icon: '🧰',
    category: 'Production',
    aiRole: 'Dismantle crew lead',
    aiRoleCn: '拆撤团队负责人',
    description: 'Coordinate a fast, safe teardown right after the show closes',
    hints: [
      { en: 'We have a four-hour strike window — the hall must be clear by midnight.', cn: '我们有四小时的拆撤时间窗口，午夜前必须清场。' },
      { en: 'Priority is the rented AV — that goes back first to avoid penalties.', cn: '首先是租赁的AV设备，先归还以避免罚款。' },
      { en: 'Wrap and label every crate against the return manifest.', cn: '对照回运清单，包装并标记每个箱子。' },
      { en: 'Keep the aisles clear for the forklift — safety first.', cn: '保持通道畅通供叉车通行——安全第一。' },
      { en: "Don't let anyone leave until the crate count matches.", cn: '在箱数核对一致之前，任何人不得离开。' },
      { en: "Once we're loaded, I need a signed handover from the freight team.", cn: '装载完成后，我需要货运团队签字交接。' },
    ],
  },
  {
    id: 'speaker-handling',
    title: 'Speaker Green Room',
    titleCn: '嘉宾候场室应对',
    icon: '🎤',
    category: 'On-Site',
    aiRole: 'Nervous keynote speaker',
    aiRoleCn: '紧张的主讲嘉宾',
    description: 'Keep a nervous, demanding keynote speaker calm before they go on',
    hints: [
      { en: "You've got fifteen minutes — everything backstage is under control.", cn: '您还有十五分钟，后台一切都在掌控之中。' },
      { en: 'Your slides are loaded and tested on the confidence monitor.', cn: '您的幻灯片已加载，并在提词屏上测试过了。' },
      { en: "I'll give you a five-minute and a one-minute cue from the wings.", cn: '我会在侧台给您五分钟和一分钟的提示。' },
      { en: "Water's on the lectern, and the clicker is fully charged.", cn: '讲台上备了水，翻页器也充满电了。' },
      { en: "If you'd like, take a moment — I'll hold the intro until you're ready.", cn: '如果您需要，可以稍作调整——我会等您准备好再开场。' },
      { en: "You're going to be great. I'll be right here the whole time.", cn: '您会表现得很棒。我会全程在这里。' },
    ],
  },

  // ── Travel & Survival pack (getting there and getting around) ────────────
  {
    id: 'airport-immigration',
    title: 'Airport & Immigration',
    titleCn: '机场入境',
    icon: '🛂',
    category: 'Travel',
    aiRole: 'Immigration officer',
    aiRoleCn: '入境官员',
    description: 'Clear passport control on arrival in Germany',
    hints: [
      { en: "I'm here for a trade show — I'm exhibiting at Messe Frankfurt.", cn: '我来参加展会——我在法兰克福展览中心参展。' },
      { en: "I'll be staying for eight days, then flying back to Shanghai.", cn: '我会停留八天，然后飞回上海。' },
      { en: "Here's my invitation letter and hotel booking.", cn: '这是我的邀请函和酒店预订单。' },
      { en: "It's a business trip — I'm not being paid by a German company.", cn: '这是商务出差——我不是由德国公司支付报酬。' },
      { en: "My return ticket is for the 15th, here on my phone.", cn: '我的返程机票是15号，在我手机上。' },
      { en: "Sorry, could you repeat that a little more slowly?", cn: '抱歉，您能稍微慢一点再说一遍吗？' },
    ],
  },
  {
    id: 'hotel-checkin',
    title: 'Hotel Check-in',
    titleCn: '酒店入住',
    icon: '🏨',
    category: 'Travel',
    aiRole: 'Hotel receptionist',
    aiRoleCn: '酒店前台',
    description: 'Check in and sort out room details at your hotel',
    hints: [
      { en: "I have a reservation under Chen — three nights, checking out Friday.", cn: '我有一个用Chen预订的房间——三晚，周五退房。' },
      { en: "Is breakfast included, and what time does it start?", cn: '含早餐吗？几点开始供应？' },
      { en: "Could I get a late check-out on the last day?", cn: '最后一天我能延迟退房吗？' },
      { en: "Is there a shuttle to the exhibition centre?", cn: '有到展览中心的班车吗？' },
      { en: "The Wi-Fi isn't working in my room — could you help?", cn: '我房间的Wi-Fi用不了，能帮忙看看吗？' },
      { en: "Could I have a receipt made out to my company?", cn: '能开一张抬头是我公司的发票吗？' },
    ],
  },
  {
    id: 'restaurant-dinner',
    title: 'Restaurant & Ordering',
    titleCn: '餐厅点餐',
    icon: '🍴',
    category: 'Travel',
    aiRole: 'Restaurant server',
    aiRoleCn: '餐厅服务员',
    description: 'Order a meal and handle the bill at a restaurant',
    hints: [
      { en: "A table for two, please — do we need a reservation?", cn: '两位，请问需要预订吗？' },
      { en: "What would you recommend that's typical of the region?", cn: '有什么本地特色菜您推荐吗？' },
      { en: "I'll have the same, but no pork — is that possible?", cn: '我要一样的，但不要猪肉——可以吗？' },
      { en: "Could we get some still water and the bread, please?", cn: '请给我们来点无气泡水和面包好吗？' },
      { en: "Could we have the bill, please? Can I pay by card?", cn: '请结账好吗？可以刷卡吗？' },
      { en: "Please keep the change — thank you, it was excellent.", cn: '不用找零了——谢谢，非常美味。' },
    ],
  },
  {
    id: 'taxi-directions',
    title: 'Taxi & Directions',
    titleCn: '打车与问路',
    icon: '🚕',
    category: 'Travel',
    aiRole: 'Taxi driver',
    aiRoleCn: '出租车司机',
    description: 'Get to the venue by taxi and ask for directions',
    hints: [
      { en: "Could you take me to the Messe, entrance east, please?", cn: '请载我到展览中心东入口好吗？' },
      { en: "Roughly how long will it take at this time of day?", cn: '这个时段大概需要多久？' },
      { en: "Could you drop me at Hall 4 rather than the main gate?", cn: '能把我放在4号馆而不是正门吗？' },
      { en: "Do you take card, or should I pay cash?", cn: '您收卡吗，还是我付现金？' },
      { en: "Could I get a receipt for the fare, please?", cn: '请给我开张车费发票好吗？' },
      { en: "Excuse me, which way is the nearest S-Bahn station?", cn: '请问最近的城铁站往哪个方向走？' },
    ],
  },
  {
    id: 'small-talk-host',
    title: 'Small Talk with a Host',
    titleCn: '与东道主寒暄',
    icon: '💬',
    category: 'Travel',
    aiRole: 'German business host',
    aiRoleCn: '德国东道主',
    description: 'Make easy small talk with a local host between meetings',
    hints: [
      { en: "This is my first time in Frankfurt — the city is beautiful.", cn: '这是我第一次来法兰克福——这座城市很美。' },
      { en: "The weather is colder than I expected, but I like it.", cn: '天气比我预想的冷，但我挺喜欢。' },
      { en: "How long have you been with the company?", cn: '您在公司工作多久了？' },
      { en: "Do you have any recommendations for dinner nearby?", cn: '附近有什么晚餐推荐吗？' },
      { en: "I'd love to see a bit of the city if there's time.", cn: '如果有时间，我很想看看这座城市。' },
      { en: "Thank you for making me feel so welcome.", cn: '谢谢您让我感到如此受欢迎。' },
    ],
  },
  {
    id: 'lost-shipment',
    title: 'Lost Luggage / Shipment',
    titleCn: '行李／货物丢失',
    icon: '🧳',
    category: 'Travel',
    aiRole: 'Airline service agent',
    aiRoleCn: '航空公司服务人员',
    description: 'Report and chase a missing bag or booth shipment',
    hints: [
      { en: "My checked bag didn't arrive — here's my baggage tag.", cn: '我托运的行李没到——这是我的行李条。' },
      { en: "It contains materials I need for a show tomorrow morning.", cn: '里面有我明早展会需要的材料。' },
      { en: "Can you tell me where it is and when it'll be delivered?", cn: '您能告诉我它在哪、什么时候能送到吗？' },
      { en: "Please deliver it to this hotel address as soon as it lands.", cn: '一到就请送到这个酒店地址。' },
      { en: "What's your reference number so I can follow up?", cn: '您的查询编号是多少，方便我后续跟进？' },
      { en: "Who do I call if it hasn't arrived by tonight?", cn: '如果今晚还没到，我该打给谁？' },
    ],
  },

  // ── Business lifecycle (before, during & around the deal) ─────────────────
  {
    id: 'client-kickoff',
    title: 'Client Kickoff',
    titleCn: '客户启动会',
    icon: '📝',
    category: 'Business',
    aiRole: 'New client giving a brief',
    aiRoleCn: '交代需求的新客户',
    description: 'Take a clear brief from a new client at the first meeting',
    hints: [
      { en: "Let's start with your goal — what does success look like for this event?", cn: '我们先从目标开始——这场活动怎样才算成功？' },
      { en: "Who is the audience, and how many are you expecting?", cn: '受众是谁，您预计有多少人？' },
      { en: "What's the budget range we're working within?", cn: '我们的预算区间大概是多少？' },
      { en: "Do you have a hard date, or is there some flexibility?", cn: '有硬性日期吗，还是有一些灵活空间？' },
      { en: "Let me repeat that back to make sure I've got it right.", cn: '让我复述一遍，确保我理解无误。' },
      { en: "I'll send a written summary by tomorrow for you to confirm.", cn: '我明天会发一份书面总结给您确认。' },
    ],
  },
  {
    id: 'contract-review',
    title: 'Contract Terms Review',
    titleCn: '合同条款审阅',
    icon: '📄',
    category: 'Business',
    aiRole: 'Client procurement lead',
    aiRoleCn: '客户采购负责人',
    description: 'Walk through key contract terms clause by clause',
    hints: [
      { en: "Let's go through the payment terms first — 50% on signing works for us.", cn: '我们先看付款条款——签约付50%对我们可行。' },
      { en: "Clause 7 on liability needs a cap — can we agree a limit?", cn: '第七条责任条款需要设上限——我们能约定一个限额吗？' },
      { en: "What's the cancellation policy if the date changes?", cn: '如果日期变更，取消政策是怎样的？' },
      { en: "We'll need that in writing before we can proceed.", cn: '在推进之前，我们需要这一点落实到书面。' },
      { en: "I'm comfortable with the scope, but not the timeline yet.", cn: '范围我可以接受，但时间安排还需再议。' },
      { en: "Let me flag this with my team and revert by Friday.", cn: '我先跟团队反映，周五前给您回复。' },
    ],
  },
  {
    id: 'booth-builder',
    title: 'Booth Builder Coordination',
    titleCn: '展台搭建协调',
    icon: '🏗️',
    category: 'Production',
    aiRole: 'Local stand contractor',
    aiRoleCn: '当地展台承包商',
    description: 'Coordinate the booth build with a local contractor on-site',
    hints: [
      { en: "Let's confirm the build schedule — when do you start on the floor?", cn: '我们确认一下搭建计划——你们什么时候进场施工？' },
      { en: "The carpet and lighting must be done before the client walkthrough.", cn: '地毯和灯光必须在客户巡视前完成。' },
      { en: "Can you match this exact Pantone for the back wall?", cn: '背景墙能做到这个准确的潘通色号吗？' },
      { en: "We need the power and rigging signed off by the hall inspector.", cn: '电力和吊装需要通过展馆检查员的验收签字。' },
      { en: "If anything slips, I need to know two hours ahead, not after.", cn: '如果有任何延误，请提前两小时告诉我，而不是事后。' },
      { en: "Let's do a snag list walk-through at the end of the day.", cn: '我们今天结束时做一次问题清单巡查。' },
    ],
  },
  {
    id: 'business-dinner',
    title: 'Client Business Dinner',
    titleCn: '客户商务晚宴',
    icon: '🍷',
    category: 'Business',
    aiRole: 'Client you are hosting',
    aiRoleCn: '你款待的客户',
    description: 'Host a client at dinner — warm, professional, not too salesy',
    hints: [
      { en: "Thank you for joining me — I hope you like the place.", cn: '谢谢您赏光——希望您喜欢这个地方。' },
      { en: "Please, order whatever you like — this is on us tonight.", cn: '请随意点——今晚我们请客。' },
      { en: "Shall we save the business talk for after we've eaten?", cn: '我们要不要吃完饭再谈正事？' },
      { en: "How did you first get into the events industry?", cn: '您最初是怎么进入活动行业的？' },
      { en: "I'd like to propose a toast — to a great partnership.", cn: '我想敬一杯——为我们美好的合作。' },
      { en: "Let me take care of the bill — it's been a real pleasure.", cn: '账单我来结——今晚非常愉快。' },
    ],
  },
  {
    id: 'stage-presentation',
    title: 'Short Stage Presentation',
    titleCn: '简短舞台演讲',
    icon: '📊',
    category: 'Business',
    aiRole: 'Session moderator & audience',
    aiRoleCn: '主持人与观众',
    description: 'Deliver a short product presentation on the show stage',
    hints: [
      { en: "Good afternoon, everyone — thank you for being here.", cn: '各位下午好——谢谢大家到场。' },
      { en: "In the next five minutes I'll show you three things.", cn: '接下来五分钟，我会向大家展示三件事。' },
      { en: "The headline is simple: we cut build time in half.", cn: '核心信息很简单：我们把搭建时间缩短了一半。' },
      { en: "Let me show you a quick example from a recent show.", cn: '我给大家看一个最近展会的简短案例。' },
      { en: "To sum up: faster, cleaner, and more sustainable.", cn: '总结一下：更快、更简洁、更环保。' },
      { en: "Happy to take questions — come find us at booth 2214.", cn: '欢迎提问——也欢迎到2214展位找我们。' },
    ],
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

export function getScenarioHints(id: string, count = 2): Hint[] {
  const scenario = getScenarioById(id);
  if (!scenario) return [];
  const shuffled = [...scenario.hints].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
